import { useEffect, useMemo, useRef } from "react";
import {
  ArcType,
  Cartesian3,
  Color,
  ColorMaterialProperty,
  ConstantProperty,
  GeoJsonDataSource,
  Ion,
  JulianDate,
  Math as CesiumMath,
  PointPrimitiveCollection,
  PolylineGraphics,
  Rectangle,
  ScreenSpaceEventHandler,
  ScreenSpaceEventType,
  SingleTileImageryProvider,
  UrlTemplateImageryProvider,
  Viewer,
  type ImageryLayer,
} from "cesium";
import "cesium/Build/Cesium/Widgets/widgets.css";
import type { Event } from "@/types/event";
import { useAuth } from "@/hooks/useAuth";
import { type GlobeLayers, isQuake } from "@/components/globe/layers";
import {
  ClusterIndex,
  desiredCellDeg,
  type GlobeCluster,
  type ScreenClusters,
} from "@/components/globe/cesium/clusters";
import {
  clusterDotStyle,
  dotPixelScaleForHeight,
  QUAKE_DOT_PIXEL_SIZE,
  quakePointStyle,
  selectionRingStyle,
} from "@/components/globe/cesium/quake-dots";
import { buildHeatCanvas } from "@/components/globe/cesium/heat";
import { createPoleUnderlayCanvas, DAYMAP_URL } from "@/components/globe/cesium/pole-underlay";
import { getTilesSession, sentinel2TemplateUrl } from "@/lib/tiles-api";
import { GlobeStatusOverlay } from "@/components/globe/cesium/GlobeStatusOverlay";

/** EOX licensing credit shown in the Cesium credit container. */
const EOX_CREDIT = "Sentinel-2 cloudless by EOX IT Services GmbH (CC-BY 4.0)";

/** Local offline contour basemap (generated by scripts/gen-contour-tiles). */
const CONTOUR_TILES_URL =
  (import.meta.env.VITE_CONTOUR_TILES_URL as string | undefined) ?? "/contours/{z}/{x}/{y}.jpg";

/**
 * Web Mercator tiles only cover this latitude band; pole caps use a generated
 * underlay that samples Sentinel colors at the Mercator edge.
 */
const WEB_MERCATOR_RECTANGLE = Rectangle.fromDegrees(-180, -85.05112878, 180, 85.05112878);

/**
 * Fallback imagery zoom ceiling used only if the tiles session omits a usable
 * `max_zoom`. The authoritative value comes from the API (`tiles_max_zoom`) via
 * `/tiles/session`, so a storage-constrained deployment can lower it in config
 * and the globe stops requesting (and the proxy stops caching) deeper tiles.
 */
const DEFAULT_MAX_IMAGERY_LEVEL = 12;

/** Deep-zoom camera limits (meters from the surface). */
const MIN_ZOOM_METERS = 80;
const MAX_ZOOM_METERS = 4.5e7;

/** Country-border GeoJSON LOD: coarse always, finer once zoomed in. */
const BORDER_LODS = [
  { url: "/geo/ne_110m_admin_0_countries.geojson", maxHeightMeters: Infinity },
  { url: "/geo/ne_50m_admin_0_countries.geojson", maxHeightMeters: 4.0e6 },
  { url: "/geo/ne_10m_admin_0_countries.geojson", maxHeightMeters: 9.0e5 },
];
/** Coastline GeoJSON, loaded once zoomed in (raster carries the wide view). */
const COASTLINE_LOD = { url: "/geo/ne_50m_land.geojson", maxHeightMeters: 4.0e6 };

/** Picked-primitive identity stored on each Cesium point/label. */
type PickId =
  | { kind: "single"; event: Event }
  | { kind: "cluster"; cluster: GlobeCluster };

interface CesiumGlobeViewportProps {
  events: Event[];
  selectedId: string | null;
  onSelect: (id: string) => void;
  onSelectCluster?: (cluster: GlobeCluster) => void;
  onClearSelection?: () => void;
  layers: GlobeLayers;
  globeTotal?: number;
  globeLoading?: boolean;
  globeLoadingMore?: boolean;
  globeEpoch?: number;
}

/**
 * CesiumJS globe implementing the same prop contract as the r3f `GlobeViewport`.
 * Imagery is a local Sentinel-2 tile pyramid served by the caching tile proxy;
 * Cesium's native quadtree LOD gives sharp, smooth zoom. Event dots, clustering,
 * selection + cluster-to-sidebar, heat overlay, vector borders, layer toggles,
 * status overlay, and live updates preserve the previous globe's behavior.
 */
export function CesiumGlobeViewport({
  events,
  selectedId,
  onSelect,
  onSelectCluster,
  onClearSelection,
  layers,
  globeTotal,
  globeLoading,
  globeLoadingMore,
  globeEpoch = 0,
}: CesiumGlobeViewportProps) {
  const { getAccessToken } = useAuth();
  const containerRef = useRef<HTMLDivElement | null>(null);
  const viewerRef = useRef<Viewer | null>(null);

  // Mutable handles for imperative Cesium objects rebuilt as props change.
  const singlesRef = useRef<PointPrimitiveCollection | null>(null);
  const clustersRef = useRef<PointPrimitiveCollection | null>(null);
  const selectionRef = useRef<PointPrimitiveCollection | null>(null);
  const heatLayerRef = useRef<ImageryLayer | null>(null);
  const indexRef = useRef<ClusterIndex>(new ClusterIndex([]));
  const lastLevelRef = useRef<number>(-1);
  const lastDotScaleKeyRef = useRef<number>(-1);
  const loadedVectorUrls = useRef<Set<string>>(new Set());
  // Latest rendered singles/clusters so the selection ring can be placed on the
  // marker actually on screen (a cluster bubble or the event's own dot).
  const lastResultRef = useRef<ScreenClusters | null>(null);
  const selectedIdRef = useRef<string | null>(selectedId);
  // Throttle the expensive index + primitive rebuild while map batches stream in
  // so accumulating ~100k points stays responsive instead of rebuilding on every
  // batch. `quakeEventsRef` lets the trailing rebuild read the latest set.
  const rebuildTimerRef = useRef<number | undefined>(undefined);
  const prevQuakeCountRef = useRef(0);
  const lastApplyAtRef = useRef(0);
  const quakeEventsRef = useRef<Event[]>([]);

  // Latest props captured in refs so the imperative Cesium callbacks (created
  // once on mount) always read current values without re-binding listeners.
  const eventsRef = useRef(events);
  const layersRef = useRef(layers);
  const onSelectRef = useRef(onSelect);
  const onSelectClusterRef = useRef(onSelectCluster);
  const onClearSelectionRef = useRef(onClearSelection);
  eventsRef.current = events;
  layersRef.current = layers;
  onSelectRef.current = onSelect;
  onSelectClusterRef.current = onSelectCluster;
  onClearSelectionRef.current = onClearSelection;
  selectedIdRef.current = selectedId;

  const quakeEvents = useMemo(() => events.filter(isQuake), [events]);
  quakeEventsRef.current = quakeEvents;

  // ── Mount: build the viewer, imagery, handlers (once) ───────────────────────
  useEffect(() => {
    if (!containerRef.current) {
      return;
    }
    // No Cesium Ion assets are used; clear the default token to avoid network.
    Ion.defaultAccessToken = "";

    const viewer = new Viewer(containerRef.current, {
      baseLayer: false,
      animation: false,
      timeline: false,
      baseLayerPicker: false,
      geocoder: false,
      homeButton: false,
      sceneModePicker: false,
      navigationHelpButton: false,
      fullscreenButton: false,
      infoBox: false,
      selectionIndicator: false,
      // Keep the credit container visible for the required EOX attribution.
    });
    viewerRef.current = viewer;

    const scene = viewer.scene;
    scene.backgroundColor = Color.fromCssColorString("#05070d");
    scene.globe.baseColor = Color.fromCssColorString("#0b1a2b");
    if (scene.skyAtmosphere) {
      scene.skyAtmosphere.show = true;
    }
    scene.globe.showGroundAtmosphere = true;
    scene.fog.enabled = true;

    const controller = scene.screenSpaceCameraController;
    controller.minimumZoomDistance = MIN_ZOOM_METERS;
    controller.maximumZoomDistance = MAX_ZOOM_METERS;
    controller.enableCollisionDetection = true;

    // Imperative primitive collections for quake dots and selection ring.
    const singles = scene.primitives.add(new PointPrimitiveCollection());
    const clusters = scene.primitives.add(new PointPrimitiveCollection());
    const selection = scene.primitives.add(new PointPrimitiveCollection());
    singlesRef.current = singles;
    clustersRef.current = clusters;
    selectionRef.current = selection;

    // Pick handling: single dot → select; cluster → fly + open sidebar; miss → clear.
    const handler = new ScreenSpaceEventHandler(scene.canvas);
    handler.setInputAction((movement: ScreenSpaceEventHandler.PositionedEvent) => {
      const picked = scene.pick(movement.position);
      const id = picked?.id as PickId | undefined;
      if (id && typeof id === "object" && "kind" in id) {
        if (id.kind === "single") {
          onSelectRef.current(id.event.id);
        } else {
          const { cluster } = id;
          viewer.camera.flyTo({
            destination: Cartesian3.fromDegrees(
              cluster.lon,
              cluster.lat,
              Math.max(viewer.camera.positionCartographic.height * 0.45, 4.0e5),
            ),
            duration: 0.8,
          });
          onSelectClusterRef.current?.(cluster);
        }
        return;
      }
      onClearSelectionRef.current?.();
    }, ScreenSpaceEventType.LEFT_CLICK);

    // Rebuild clusters while zooming (debounced) and once the camera settles.
    let clusterRebuildTimer: number | undefined;
    const scheduleClusterRebuild = () => {
      if (clusterRebuildTimer) {
        window.clearTimeout(clusterRebuildTimer);
      }
      clusterRebuildTimer = window.setTimeout(() => {
        clusterRebuildTimer = undefined;
        rebuildClusters();
        applySelectionHighlight();
      }, 120);
    };
    const onCameraSettle = () => {
      if (clusterRebuildTimer) {
        window.clearTimeout(clusterRebuildTimer);
        clusterRebuildTimer = undefined;
      }
      rebuildClusters();
      applySelectionHighlight();
      // Refine border/coastline LOD for the new zoom; idempotent (skips already
      // loaded levels). Camera-driven so it no longer runs per streamed batch.
      void loadVectorOverlays();
    };
    viewer.camera.changed.addEventListener(scheduleClusterRebuild);
    viewer.camera.moveEnd.addEventListener(onCameraSettle);

    // Imagery stack (bottom → top): equirectangular pole underlay, optional
    // contour Mercator tiles, Sentinel Mercator tiles. Mercator layers declare
    // WEB_MERCATOR_RECTANGLE so Cesium composites the underlay at the poles.
    let cancelled = false;
    let sentinelLayer: ImageryLayer | null = null;

    const installPoleUnderlay = async (tilesToken?: string) => {
      const addProvider = async (url: string) => {
        const provider = await SingleTileImageryProvider.fromUrl(url, {
          rectangle: Rectangle.fromDegrees(-180, -90, 180, 90),
        });
        if (!cancelled && !viewer.isDestroyed()) {
          viewer.imageryLayers.addImageryProvider(provider, 0);
        }
      };

      try {
        const canvas = await createPoleUnderlayCanvas(tilesToken);
        // JPEG keeps the underlay fully opaque — Cesium can leave holes with PNG alpha.
        await addProvider(canvas.toDataURL("image/jpeg", 0.92));
      } catch {
        try {
          await addProvider(DAYMAP_URL);
        } catch {
          // Polar caps fall back to globe.baseColor.
        }
      }
    };

    const installContourFallback = async () => {
      const probeUrl = CONTOUR_TILES_URL.replace("{z}", "0")
        .replace("{x}", "0")
        .replace("{y}", "0");
      // No contour tiles served (404 / network error): skip the fallback layer.
      const available = await fetch(probeUrl, { method: "GET" })
        .then((res) => res.ok)
        .catch(() => false);
      if (!available || cancelled || viewer.isDestroyed()) {
        return;
      }
      const contourLayer = viewer.imageryLayers.addImageryProvider(
        new UrlTemplateImageryProvider({
          url: CONTOUR_TILES_URL,
          maximumLevel: 8,
          rectangle: WEB_MERCATOR_RECTANGLE,
          credit: "Elevation contours (ETOPO 2022, public domain)",
        }),
        1,
      );
      contourLayer.show = true;
    };

    // Fetch a tiles token, then add the Sentinel imagery layer above contours.
    let refreshTimer: number | undefined;
    const installSentinel = async (existingToken?: string) => {
      const token = existingToken ?? (await getAccessToken());
      if (!token || cancelled) {
        return;
      }
      let session;
      try {
        session = await getTilesSession(token);
      } catch {
        return; // Offline / unauthorized: contour fallback remains visible.
      }
      if (cancelled || viewer.isDestroyed()) {
        return;
      }
      const maximumLevel =
        Number.isFinite(session.max_zoom) && session.max_zoom > 0
          ? session.max_zoom
          : DEFAULT_MAX_IMAGERY_LEVEL;
      const provider = new UrlTemplateImageryProvider({
        url: sentinel2TemplateUrl(session.token),
        maximumLevel,
        rectangle: WEB_MERCATOR_RECTANGLE,
        credit: EOX_CREDIT,
      });
      if (sentinelLayer) {
        viewer.imageryLayers.remove(sentinelLayer, true);
        sentinelLayer = null;
      }
      sentinelLayer = viewer.imageryLayers.addImageryProvider(provider);
      // Refresh the token shortly before expiry so the imagery URL stays valid.
      const refreshMs = Math.max((session.expires_in - 300) * 1000, 60_000);
      refreshTimer = window.setTimeout(() => void installSentinel(), refreshMs);
    };

    void (async () => {
      const accessToken = await getAccessToken();
      let tilesToken: string | undefined;
      if (accessToken) {
        try {
          const session = await getTilesSession(accessToken);
          tilesToken = session.token;
        } catch {
          // Pole fill uses daymap + fallback colors when the session is unavailable.
        }
      }
      await installPoleUnderlay(tilesToken);
      await installContourFallback();
      await installSentinel(accessToken ?? undefined);
    })();

    void loadVectorOverlays();
    rebuildClusters();

    return () => {
      cancelled = true;
      if (clusterRebuildTimer) {
        window.clearTimeout(clusterRebuildTimer);
      }
      if (rebuildTimerRef.current !== undefined) {
        window.clearTimeout(rebuildTimerRef.current);
        rebuildTimerRef.current = undefined;
      }
      if (refreshTimer) {
        window.clearTimeout(refreshTimer);
      }
      viewer.camera.changed.removeEventListener(scheduleClusterRebuild);
      viewer.camera.moveEnd.removeEventListener(onCameraSettle);
      handler.destroy();
      if (!viewer.isDestroyed()) {
        viewer.destroy();
      }
      viewerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount-once viewer; props read via refs
  }, []);

  // ── Cluster dot rebuild ─────────────────────────────────────────────────────
  function rebuildClusters() {
    const viewer = viewerRef.current;
    const singles = singlesRef.current;
    const clusters = clustersRef.current;
    if (!viewer || !singles || !clusters || viewer.isDestroyed()) {
      return;
    }

    if (!layersRef.current.quakeDots) {
      singles.removeAll();
      clusters.removeAll();
      lastLevelRef.current = -1;
      lastDotScaleKeyRef.current = -1;
      lastResultRef.current = null;
      return;
    }

    const camera = viewer.camera;
    const height = camera.positionCartographic?.height ?? MAX_ZOOM_METERS;
    const fovy = (viewer.scene.camera.frustum as { fovy?: number }).fovy ?? CesiumMath.toRadians(60);
    const canvasHeight = viewer.scene.canvas.clientHeight || 1;
    const deg = desiredCellDeg(height, fovy, canvasHeight);
    const { level, result } = indexRef.current.forDesiredDeg(deg);
    lastResultRef.current = result;

    const dotScale = dotPixelScaleForHeight(height, MAX_ZOOM_METERS);
    const dotScaleKey = Math.round(dotScale * 20);

    // Skip when cluster LOD and dot size are both unchanged.
    if (level === lastLevelRef.current && dotScaleKey === lastDotScaleKeyRef.current) {
      return;
    }
    lastLevelRef.current = level;
    lastDotScaleKeyRef.current = dotScaleKey;

    singles.removeAll();
    clusters.removeAll();

    for (const event of result.singles) {
      singles.add({
        position: Cartesian3.fromDegrees(event.location.lon, event.location.lat),
        ...quakePointStyle(event.severity, dotScale),
        id: { kind: "single", event } satisfies PickId,
      });
    }

    for (const cluster of result.clusters) {
      const position = Cartesian3.fromDegrees(cluster.lon, cluster.lat);
      const pickId: PickId = { kind: "cluster", cluster };
      clusters.add({
        position,
        ...clusterDotStyle(cluster.severity, dotScale),
        id: pickId,
      });
    }
  }

  // ── Selection highlight, aligned to the visible marker ──────────────────────
  // Places the ring on the marker the user actually sees: the cluster bubble
  // when the selected event is aggregated into one (anchored on the top-impact
  // member, which may differ from other members), otherwise the event's own dot. Reads refs so
  // it can be called from both the mount-time `rebuildClusters` and the effect.
  function applySelectionHighlight() {
    const selection = selectionRef.current;
    if (!selection) {
      return;
    }
    selection.removeAll();
    const selectedId = selectedIdRef.current;
    if (!selectedId) {
      return;
    }

    const viewer = viewerRef.current;
    const height = viewer?.camera.positionCartographic?.height ?? MAX_ZOOM_METERS;
    const dotScale = dotPixelScaleForHeight(height, MAX_ZOOM_METERS);

    const cluster = lastResultRef.current?.clusters.find((item) =>
      item.members.some((member) => member.id === selectedId),
    );
    if (cluster) {
      const position = Cartesian3.fromDegrees(cluster.lon, cluster.lat);
      selection.add({ position, ...clusterDotStyle(cluster.severity, dotScale) });
      selection.add({
        position,
        ...selectionRingStyle(QUAKE_DOT_PIXEL_SIZE * dotScale + 10),
      });
      return;
    }

    const event =
      lastResultRef.current?.singles.find((item) => item.id === selectedId) ??
      eventsRef.current.find((item) => item.id === selectedId);
    if (!event) {
      return;
    }
    const position = Cartesian3.fromDegrees(event.location.lon, event.location.lat);
    // Draw the dot too so a selection that is not part of the current LOD (e.g.
    // hydrated from detail) is still visible inside the ring.
    selection.add({
      position,
      ...quakePointStyle(event.severity, dotScale, QUAKE_DOT_PIXEL_SIZE + 2),
    });
    selection.add({
      position,
      ...selectionRingStyle((QUAKE_DOT_PIXEL_SIZE + 2) * dotScale + 8),
    });
  }

  // ── Vector overlays (borders + coastline), camera-height LOD ────────────────
  async function loadVectorOverlays() {
    const viewer = viewerRef.current;
    if (!viewer || viewer.isDestroyed()) {
      return;
    }
    const height = viewer.camera.positionCartographic?.height ?? MAX_ZOOM_METERS;

    const wanted: { url: string; color: string; width: number }[] = [];
    // Finest qualifying border level only (last wins) + coastline when zoomed.
    let border = BORDER_LODS[0];
    for (const lod of BORDER_LODS) {
      if (height <= lod.maxHeightMeters) {
        border = lod;
      }
    }
    wanted.push({ url: border.url, color: "#cdf3ea", width: 1 });
    if (height <= COASTLINE_LOD.maxHeightMeters) {
      wanted.push({ url: COASTLINE_LOD.url, color: "#bfe9ff", width: 1 });
    }

    for (const item of wanted) {
      if (loadedVectorUrls.current.has(item.url)) {
        continue;
      }
      loadedVectorUrls.current.add(item.url);
      try {
        const ds = await GeoJsonDataSource.load(item.url, {
          stroke: Color.fromCssColorString(item.color).withAlpha(0.5),
          fill: Color.TRANSPARENT,
          strokeWidth: item.width,
        });
        // Replace every loaded polygon with a plain outline polyline drawn with
        // straight (ArcType.NONE), non-ground-clamped segments. Cesium's default
        // ground-clamped rhumb subdivision over the dense Natural Earth polygons
        // explodes the vertex count and crashes the renderer ("Too many
        // properties to enumerate"); filled polygon geometry with a forced
        // arcType/height fails differently. Since the fill is transparent and v1
        // uses a flat ellipsoid (no 3D terrain), straight chords between the
        // already-dense vertices look identical and never subdivide.
        const material = new ColorMaterialProperty(
          Color.fromCssColorString(item.color).withAlpha(0.5),
        );
        const now = JulianDate.now();
        for (const entity of ds.entities.values) {
          if (entity.polygon) {
            const hierarchy = entity.polygon.hierarchy?.getValue(now);
            const positions = hierarchy?.positions;
            entity.polygon = undefined;
            if (positions && positions.length > 1) {
              entity.polyline = new PolylineGraphics({
                positions,
                width: item.width,
                material,
                arcType: ArcType.NONE,
                clampToGround: false,
              });
            }
          } else if (entity.polyline) {
            entity.polyline.material = material;
            entity.polyline.width = new ConstantProperty(item.width);
            entity.polyline.arcType = new ConstantProperty(ArcType.NONE);
            entity.polyline.clampToGround = new ConstantProperty(false);
          }
        }
        if (viewer.isDestroyed()) {
          return;
        }
        await viewer.dataSources.add(ds);
      } catch {
        loadedVectorUrls.current.delete(item.url);
      }
    }
  }

  // ── React to event-set changes: rebuild the cluster index (throttled) ───────
  // While batches stream in (the set only grows), a full `O(n)` index + Cesium
  // primitive rebuild on every batch makes a large load `O(n²)` and janky. So we
  // render the first batch immediately, coalesce intermediate batches to at most
  // one rebuild per window, and always render the final batch via a trailing
  // timer that reads the latest set from `quakeEventsRef`.
  useEffect(() => {
    const REBUILD_THROTTLE_MS = 400;

    const applyEventSet = () => {
      const data = quakeEventsRef.current;
      lastApplyAtRef.current = performance.now();
      prevQuakeCountRef.current = data.length;
      indexRef.current = new ClusterIndex(data);
      lastLevelRef.current = -1;
      lastDotScaleKeyRef.current = -1;
      rebuildClusters();
      applySelectionHighlight();
    };

    const grewWhileStreaming =
      prevQuakeCountRef.current > 0 && quakeEvents.length > prevQuakeCountRef.current;
    const elapsed = performance.now() - lastApplyAtRef.current;

    if (!grewWhileStreaming || elapsed >= REBUILD_THROTTLE_MS) {
      // First load, filter reset/shrink, or throttle window elapsed: render now.
      if (rebuildTimerRef.current !== undefined) {
        window.clearTimeout(rebuildTimerRef.current);
        rebuildTimerRef.current = undefined;
      }
      applyEventSet();
    } else if (rebuildTimerRef.current === undefined) {
      // Trailing rebuild for the rest of the window; guarantees the last batch
      // renders even if it lands mid-window (timer reads the latest set).
      rebuildTimerRef.current = window.setTimeout(() => {
        rebuildTimerRef.current = undefined;
        applyEventSet();
      }, REBUILD_THROTTLE_MS - elapsed);
    }
  }, [quakeEvents]);

  // ── React to layer toggles (dots) ───────────────────────────────────────────
  useEffect(() => {
    lastLevelRef.current = -1;
    lastDotScaleKeyRef.current = -1;
    rebuildClusters();
    applySelectionHighlight();
  }, [layers.quakeDots]);

  // ── Heat overlay: rebuild canvas layer on toggle / events / epoch ───────────
  useEffect(() => {
    const viewer = viewerRef.current;
    if (!viewer || viewer.isDestroyed()) {
      return;
    }
    const removeHeat = () => {
      if (heatLayerRef.current) {
        viewer.imageryLayers.remove(heatLayerRef.current, true);
        heatLayerRef.current = null;
      }
    };

    if (!layers.quakeHeat) {
      removeHeat();
      return;
    }

    // Debounce heavy repaints while batches stream in.
    const debounceMs = quakeEvents.length > 2_500 || globeLoadingMore ? 400 : 0;
    const timer = window.setTimeout(() => {
      if (viewer.isDestroyed()) {
        return;
      }
      const canvas = buildHeatCanvas(quakeEvents);
      removeHeat();
      if (!canvas) {
        return;
      }
      void SingleTileImageryProvider.fromUrl(canvas.toDataURL("image/png"), {
        rectangle: Rectangle.fromDegrees(-180, -90, 180, 90),
      }).then((provider) => {
        if (viewer.isDestroyed() || !layersRef.current.quakeHeat) {
          return;
        }
        heatLayerRef.current = viewer.imageryLayers.addImageryProvider(provider);
      });
    }, debounceMs);

    return () => window.clearTimeout(timer);
  }, [layers.quakeHeat, quakeEvents, globeEpoch, globeLoadingMore]);

  // ── Selection highlight ─────────────────────────────────────────────────────
  useEffect(() => {
    applySelectionHighlight();
  }, [selectedId, events]);

  return (
    <div className="relative size-full min-h-full overflow-hidden bg-[#05070d]">
      <div ref={containerRef} className="absolute inset-0" />
      {/* Cinematic vignette to focus the eye on the globe. */}
      <div className="pointer-events-none absolute inset-0 [background:radial-gradient(circle_at_50%_45%,transparent_42%,rgba(5,7,13,0.55)_100%)]" />
      <GlobeStatusOverlay
        events={events}
        globeTotal={globeTotal}
        globeLoading={globeLoading}
        globeLoadingMore={globeLoadingMore}
      />
    </div>
  );
}
