import { useEffect, useMemo, useRef } from "react";
import {
  ArcType,
  Cartesian3,
  Color,
  ColorMaterialProperty,
  ConstantProperty,
  GeoJsonDataSource,
  HorizontalOrigin,
  Ion,
  JulianDate,
  LabelCollection,
  LabelStyle,
  Math as CesiumMath,
  NearFarScalar,
  PointPrimitiveCollection,
  PolylineGraphics,
  Rectangle,
  ScreenSpaceEventHandler,
  ScreenSpaceEventType,
  SingleTileImageryProvider,
  UrlTemplateImageryProvider,
  VerticalOrigin,
  Viewer,
  type ImageryLayer,
} from "cesium";
import "cesium/Build/Cesium/Widgets/widgets.css";
import type { Event } from "@/types/event";
import { useAuth } from "@/hooks/useAuth";
import { type GlobeLayers, isQuake } from "@/components/globe/layers";
import {
  ClusterIndex,
  desiredCellDeg,
  type GlobeCluster,
  type ScreenClusters,
} from "@/components/globe/cesium/clusters";
import { severityToCesiumColor } from "@/components/globe/cesium/severity-colors";
import { buildHeatCanvas } from "@/components/globe/cesium/heat";
import { getTilesSession, sentinel2TemplateUrl } from "@/lib/tiles-api";
import { GlobeStatusOverlay } from "@/components/globe/cesium/GlobeStatusOverlay";

/** EOX licensing credit shown in the Cesium credit container. */
const EOX_CREDIT = "Sentinel-2 cloudless by EOX IT Services GmbH (CC-BY 4.0)";

/** Local offline contour basemap (generated by scripts/gen-contour-tiles). */
const CONTOUR_TILES_URL =
  (import.meta.env.VITE_CONTOUR_TILES_URL as string | undefined) ?? "/contours/{z}/{x}/{y}.jpg";

/**
 * Fallback imagery zoom ceiling used only if the tiles session omits a usable
 * `max_zoom`. The authoritative value comes from the API (`tiles_max_zoom`) via
 * `/tiles/session`, so a storage-constrained deployment can lower it in config
 * and the globe stops requesting (and the proxy stops caching) deeper tiles.
 */
const DEFAULT_MAX_IMAGERY_LEVEL = 12;

/** Deep-zoom camera limits (meters from the surface). */
const MIN_ZOOM_METERS = 80;
const MAX_ZOOM_METERS = 4.5e7;

/** Country-border GeoJSON LOD: coarse always, finer once zoomed in. */
const BORDER_LODS = [
  { url: "/geo/ne_110m_admin_0_countries.geojson", maxHeightMeters: Infinity },
  { url: "/geo/ne_50m_admin_0_countries.geojson", maxHeightMeters: 4.0e6 },
  { url: "/geo/ne_10m_admin_0_countries.geojson", maxHeightMeters: 9.0e5 },
];
/** Coastline GeoJSON, loaded once zoomed in (raster carries the wide view). */
const COASTLINE_LOD = { url: "/geo/ne_50m_land.geojson", maxHeightMeters: 4.0e6 };

/** Picked-primitive identity stored on each Cesium point/label. */
type PickId =
  | { kind: "single"; event: Event }
  | { kind: "cluster"; cluster: GlobeCluster };

interface CesiumGlobeViewportProps {
  events: Event[];
  selectedId: string | null;
  onSelect: (id: string) => void;
  onSelectCluster?: (cluster: GlobeCluster) => void;
  onClearSelection?: () => void;
  layers: GlobeLayers;
  globeTotal?: number;
  globeLoading?: boolean;
  globeLoadingMore?: boolean;
  globeEpoch?: number;
}

/**
 * CesiumJS globe implementing the same prop contract as the r3f `GlobeViewport`.
 * Imagery is a local Sentinel-2 tile pyramid served by the caching tile proxy;
 * Cesium's native quadtree LOD gives sharp, smooth zoom. Event dots, clustering,
 * selection + cluster-to-sidebar, heat overlay, vector borders, layer toggles,
 * status overlay, and live updates preserve the previous globe's behavior.
 */
export function CesiumGlobeViewport({
  events,
  selectedId,
  onSelect,
  onSelectCluster,
  onClearSelection,
  layers,
  globeTotal,
  globeLoading,
  globeLoadingMore,
  globeEpoch = 0,
}: CesiumGlobeViewportProps) {
  const { getAccessToken } = useAuth();
  const containerRef = useRef<HTMLDivElement | null>(null);
  const viewerRef = useRef<Viewer | null>(null);

  // Mutable handles for imperative Cesium objects rebuilt as props change.
  const singlesRef = useRef<PointPrimitiveCollection | null>(null);
  const clustersRef = useRef<PointPrimitiveCollection | null>(null);
  const labelsRef = useRef<LabelCollection | null>(null);
  const selectionRef = useRef<PointPrimitiveCollection | null>(null);
  const heatLayerRef = useRef<ImageryLayer | null>(null);
  const indexRef = useRef<ClusterIndex>(new ClusterIndex([]));
  const lastLevelRef = useRef<number>(-1);
  const loadedVectorUrls = useRef<Set<string>>(new Set());
  // Latest rendered singles/clusters so the selection ring can be placed on the
  // marker actually on screen (a cluster bubble or the event's own dot).
  const lastResultRef = useRef<ScreenClusters | null>(null);
  const selectedIdRef = useRef<string | null>(selectedId);

  // Latest props captured in refs so the imperative Cesium callbacks (created
  // once on mount) always read current values without re-binding listeners.
  const eventsRef = useRef(events);
  const layersRef = useRef(layers);
  const onSelectRef = useRef(onSelect);
  const onSelectClusterRef = useRef(onSelectCluster);
  const onClearSelectionRef = useRef(onClearSelection);
  eventsRef.current = events;
  layersRef.current = layers;
  onSelectRef.current = onSelect;
  onSelectClusterRef.current = onSelectCluster;
  onClearSelectionRef.current = onClearSelection;
  selectedIdRef.current = selectedId;

  const quakeEvents = useMemo(() => events.filter(isQuake), [events]);

  // ── Mount: build the viewer, imagery, handlers (once) ───────────────────────
  useEffect(() => {
    if (!containerRef.current) {
      return;
    }
    // No Cesium Ion assets are used; clear the default token to avoid network.
    Ion.defaultAccessToken = "";

    const viewer = new Viewer(containerRef.current, {
      baseLayer: false,
      animation: false,
      timeline: false,
      baseLayerPicker: false,
      geocoder: false,
      homeButton: false,
      sceneModePicker: false,
      navigationHelpButton: false,
      fullscreenButton: false,
      infoBox: false,
      selectionIndicator: false,
      // Keep the credit container visible for the required EOX attribution.
    });
    viewerRef.current = viewer;

    const scene = viewer.scene;
    scene.backgroundColor = Color.fromCssColorString("#05070d");
    scene.globe.baseColor = Color.fromCssColorString("#0b1a2b");
    if (scene.skyAtmosphere) {
      scene.skyAtmosphere.show = true;
    }
    scene.globe.showGroundAtmosphere = true;
    scene.fog.enabled = true;

    const controller = scene.screenSpaceCameraController;
    controller.minimumZoomDistance = MIN_ZOOM_METERS;
    controller.maximumZoomDistance = MAX_ZOOM_METERS;
    controller.enableCollisionDetection = true;

    // Imperative primitive collections for dots, clusters, labels, selection.
    const singles = scene.primitives.add(new PointPrimitiveCollection());
    const clusters = scene.primitives.add(new PointPrimitiveCollection());
    const labels = scene.primitives.add(new LabelCollection());
    const selection = scene.primitives.add(new PointPrimitiveCollection());
    singlesRef.current = singles;
    clustersRef.current = clusters;
    labelsRef.current = labels;
    selectionRef.current = selection;

    // Pick handling: single dot → select; cluster → fly + open sidebar; miss → clear.
    const handler = new ScreenSpaceEventHandler(scene.canvas);
    handler.setInputAction((movement: ScreenSpaceEventHandler.PositionedEvent) => {
      const picked = scene.pick(movement.position);
      const id = picked?.id as PickId | undefined;
      if (id && typeof id === "object" && "kind" in id) {
        if (id.kind === "single") {
          onSelectRef.current(id.event.id);
        } else {
          const { cluster } = id;
          viewer.camera.flyTo({
            destination: Cartesian3.fromDegrees(
              cluster.lon,
              cluster.lat,
              Math.max(viewer.camera.positionCartographic.height * 0.45, 4.0e5),
            ),
            duration: 0.8,
          });
          onSelectClusterRef.current?.(cluster);
        }
        return;
      }
      onClearSelectionRef.current?.();
    }, ScreenSpaceEventType.LEFT_CLICK);

    // Rebuild clusters when the camera settles (zoom level may have changed),
    // then re-anchor the selection ring onto the now-current marker.
    const onCameraSettle = () => {
      rebuildClusters();
      applySelectionHighlight();
    };
    viewer.camera.moveEnd.addEventListener(onCameraSettle);

    // Offline fallback: the local ETOPO contour basemap is added *beneath*
    // Sentinel only when its tiles actually exist (probe z0). Adding it
    // unconditionally floods the console with 404s on every tile when the
    // contours haven't been generated (scripts/gen-contour-tiles.sh), so we
    // gate it; once generated it shows through wherever Sentinel is missing.
    let cancelled = false;
    const installContourFallback = async () => {
      const probeUrl = CONTOUR_TILES_URL.replace("{z}", "0")
        .replace("{x}", "0")
        .replace("{y}", "0");
      // No contour tiles served (404 / network error): skip the fallback layer.
      const available = await fetch(probeUrl, { method: "GET" })
        .then((res) => res.ok)
        .catch(() => false);
      if (!available || cancelled || viewer.isDestroyed()) {
        return;
      }
      // Index 0 keeps the contour layer below the Sentinel layer regardless of
      // which async install resolves first.
      const contourLayer = viewer.imageryLayers.addImageryProvider(
        new UrlTemplateImageryProvider({
          url: CONTOUR_TILES_URL,
          maximumLevel: 8,
          credit: "Elevation contours (ETOPO 2022, public domain)",
        }),
        0,
      );
      contourLayer.show = true;
    };
    void installContourFallback();

    // Fetch a tiles token, then add the Sentinel imagery layer above contours.
    let refreshTimer: number | undefined;
    const installSentinel = async () => {
      const token = await getAccessToken();
      if (!token || cancelled) {
        return;
      }
      let session;
      try {
        session = await getTilesSession(token);
      } catch {
        return; // Offline / unauthorized: contour fallback remains visible.
      }
      if (cancelled || viewer.isDestroyed()) {
        return;
      }
      const maximumLevel =
        Number.isFinite(session.max_zoom) && session.max_zoom > 0
          ? session.max_zoom
          : DEFAULT_MAX_IMAGERY_LEVEL;
      const provider = new UrlTemplateImageryProvider({
        url: sentinel2TemplateUrl(session.token),
        maximumLevel,
        credit: EOX_CREDIT,
      });
      viewer.imageryLayers.addImageryProvider(provider);
      // Refresh the token shortly before expiry so the imagery URL stays valid.
      const refreshMs = Math.max((session.expires_in - 300) * 1000, 60_000);
      refreshTimer = window.setTimeout(() => void installSentinel(), refreshMs);
    };
    void installSentinel();

    void loadVectorOverlays();
    rebuildClusters();

    return () => {
      cancelled = true;
      if (refreshTimer) {
        window.clearTimeout(refreshTimer);
      }
      viewer.camera.moveEnd.removeEventListener(onCameraSettle);
      handler.destroy();
      if (!viewer.isDestroyed()) {
        viewer.destroy();
      }
      viewerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount-once viewer; props read via refs
  }, []);

  // ── Cluster (dots + bubbles) rebuild ────────────────────────────────────────
  function rebuildClusters() {
    const viewer = viewerRef.current;
    const singles = singlesRef.current;
    const clusters = clustersRef.current;
    const labels = labelsRef.current;
    if (!viewer || !singles || !clusters || !labels || viewer.isDestroyed()) {
      return;
    }

    if (!layersRef.current.quakeDots) {
      singles.removeAll();
      clusters.removeAll();
      labels.removeAll();
      lastLevelRef.current = -1;
      lastResultRef.current = null;
      return;
    }

    const camera = viewer.camera;
    const height = camera.positionCartographic?.height ?? MAX_ZOOM_METERS;
    const fovy = (viewer.scene.camera.frustum as { fovy?: number }).fovy ?? CesiumMath.toRadians(60);
    const canvasHeight = viewer.scene.canvas.clientHeight || 1;
    const deg = desiredCellDeg(height, fovy, canvasHeight);
    const { level, result } = indexRef.current.forDesiredDeg(deg);
    lastResultRef.current = result;

    // Skip the rebuild when neither the LOD level nor the event set changed.
    if (level === lastLevelRef.current) {
      return;
    }
    lastLevelRef.current = level;

    singles.removeAll();
    clusters.removeAll();
    labels.removeAll();

    for (const event of result.singles) {
      singles.add({
        position: Cartesian3.fromDegrees(event.location.lon, event.location.lat),
        color: severityToCesiumColor(event.severity),
        pixelSize: 7,
        scaleByDistance: new NearFarScalar(1.0e5, 1.6, 1.5e7, 0.7),
        id: { kind: "single", event } satisfies PickId,
      });
    }

    for (const cluster of result.clusters) {
      const position = Cartesian3.fromDegrees(cluster.lon, cluster.lat);
      const pickId: PickId = { kind: "cluster", cluster };
      clusters.add({
        position,
        color: cluster.color.withAlpha(0.85),
        pixelSize: Math.min(16 + Math.log10(cluster.count) * 9, 46),
        id: pickId,
      });
      labels.add({
        position,
        text: cluster.count.toLocaleString(),
        font: "600 12px Inter, system-ui, sans-serif",
        fillColor: Color.WHITE,
        style: LabelStyle.FILL_AND_OUTLINE,
        outlineColor: Color.BLACK.withAlpha(0.6),
        outlineWidth: 2,
        horizontalOrigin: HorizontalOrigin.CENTER,
        verticalOrigin: VerticalOrigin.CENTER,
        id: pickId,
      });
    }
  }

  // ── Selection highlight, aligned to the visible marker ──────────────────────
  // Places the ring on the marker the user actually sees: the cluster bubble
  // when the selected event is aggregated into one (its centroid differs from
  // the member's raw coordinate), otherwise the event's own dot. Reads refs so
  // it can be called from both the mount-time `rebuildClusters` and the effect.
  function applySelectionHighlight() {
    const selection = selectionRef.current;
    if (!selection) {
      return;
    }
    selection.removeAll();
    const selectedId = selectedIdRef.current;
    if (!selectedId) {
      return;
    }

    const cluster = lastResultRef.current?.clusters.find((item) =>
      item.members.some((member) => member.id === selectedId),
    );
    if (cluster) {
      const bubble = Math.min(16 + Math.log10(cluster.count) * 9, 46);
      selection.add({
        position: Cartesian3.fromDegrees(cluster.lon, cluster.lat),
        color: Color.WHITE.withAlpha(0.0),
        pixelSize: bubble + 10,
        outlineColor: Color.WHITE,
        outlineWidth: 2.5,
      });
      return;
    }

    const event =
      lastResultRef.current?.singles.find((item) => item.id === selectedId) ??
      eventsRef.current.find((item) => item.id === selectedId);
    if (!event) {
      return;
    }
    const position = Cartesian3.fromDegrees(event.location.lon, event.location.lat);
    // Draw the dot too so a selection that is not part of the current LOD (e.g.
    // hydrated from detail) is still visible inside the ring.
    selection.add({ position, color: severityToCesiumColor(event.severity), pixelSize: 9 });
    selection.add({
      position,
      color: Color.WHITE.withAlpha(0.0),
      pixelSize: 20,
      outlineColor: Color.WHITE,
      outlineWidth: 2.5,
    });
  }

  // ── Vector overlays (borders + coastline), camera-height LOD ────────────────
  async function loadVectorOverlays() {
    const viewer = viewerRef.current;
    if (!viewer || viewer.isDestroyed()) {
      return;
    }
    const height = viewer.camera.positionCartographic?.height ?? MAX_ZOOM_METERS;

    const wanted: { url: string; color: string; width: number }[] = [];
    // Finest qualifying border level only (last wins) + coastline when zoomed.
    let border = BORDER_LODS[0];
    for (const lod of BORDER_LODS) {
      if (height <= lod.maxHeightMeters) {
        border = lod;
      }
    }
    wanted.push({ url: border.url, color: "#cdf3ea", width: 1 });
    if (height <= COASTLINE_LOD.maxHeightMeters) {
      wanted.push({ url: COASTLINE_LOD.url, color: "#bfe9ff", width: 1 });
    }

    for (const item of wanted) {
      if (loadedVectorUrls.current.has(item.url)) {
        continue;
      }
      loadedVectorUrls.current.add(item.url);
      try {
        const ds = await GeoJsonDataSource.load(item.url, {
          stroke: Color.fromCssColorString(item.color).withAlpha(0.5),
          fill: Color.TRANSPARENT,
          strokeWidth: item.width,
        });
        // Replace every loaded polygon with a plain outline polyline drawn with
        // straight (ArcType.NONE), non-ground-clamped segments. Cesium's default
        // ground-clamped rhumb subdivision over the dense Natural Earth polygons
        // explodes the vertex count and crashes the renderer ("Too many
        // properties to enumerate"); filled polygon geometry with a forced
        // arcType/height fails differently. Since the fill is transparent and v1
        // uses a flat ellipsoid (no 3D terrain), straight chords between the
        // already-dense vertices look identical and never subdivide.
        const material = new ColorMaterialProperty(
          Color.fromCssColorString(item.color).withAlpha(0.5),
        );
        const now = JulianDate.now();
        for (const entity of ds.entities.values) {
          if (entity.polygon) {
            const hierarchy = entity.polygon.hierarchy?.getValue(now);
            const positions = hierarchy?.positions;
            entity.polygon = undefined;
            if (positions && positions.length > 1) {
              entity.polyline = new PolylineGraphics({
                positions,
                width: item.width,
                material,
                arcType: ArcType.NONE,
                clampToGround: false,
              });
            }
          } else if (entity.polyline) {
            entity.polyline.material = material;
            entity.polyline.width = new ConstantProperty(item.width);
            entity.polyline.arcType = new ConstantProperty(ArcType.NONE);
            entity.polyline.clampToGround = new ConstantProperty(false);
          }
        }
        if (viewer.isDestroyed()) {
          return;
        }
        await viewer.dataSources.add(ds);
      } catch {
        loadedVectorUrls.current.delete(item.url);
      }
    }
  }

  // ── React to event-set changes: new cluster index, force rebuild ────────────
  useEffect(() => {
    indexRef.current = new ClusterIndex(quakeEvents);
    lastLevelRef.current = -1;
    rebuildClusters();
    applySelectionHighlight();
    void loadVectorOverlays();
  }, [quakeEvents]);

  // ── React to layer toggles (dots) ───────────────────────────────────────────
  useEffect(() => {
    lastLevelRef.current = -1;
    rebuildClusters();
    applySelectionHighlight();
  }, [layers.quakeDots]);

  // ── Heat overlay: rebuild canvas layer on toggle / events / epoch ───────────
  useEffect(() => {
    const viewer = viewerRef.current;
    if (!viewer || viewer.isDestroyed()) {
      return;
    }
    const removeHeat = () => {
      if (heatLayerRef.current) {
        viewer.imageryLayers.remove(heatLayerRef.current, true);
        heatLayerRef.current = null;
      }
    };

    if (!layers.quakeHeat) {
      removeHeat();
      return;
    }

    // Debounce heavy repaints while batches stream in.
    const debounceMs = quakeEvents.length > 2_500 || globeLoadingMore ? 400 : 0;
    const timer = window.setTimeout(() => {
      if (viewer.isDestroyed()) {
        return;
      }
      const canvas = buildHeatCanvas(quakeEvents);
      removeHeat();
      if (!canvas) {
        return;
      }
      void SingleTileImageryProvider.fromUrl(canvas.toDataURL("image/png"), {
        rectangle: Rectangle.fromDegrees(-180, -90, 180, 90),
      }).then((provider) => {
        if (viewer.isDestroyed() || !layersRef.current.quakeHeat) {
          return;
        }
        heatLayerRef.current = viewer.imageryLayers.addImageryProvider(provider);
      });
    }, debounceMs);

    return () => window.clearTimeout(timer);
  }, [layers.quakeHeat, quakeEvents, globeEpoch, globeLoadingMore]);

  // ── Selection highlight ─────────────────────────────────────────────────────
  useEffect(() => {
    applySelectionHighlight();
  }, [selectedId, events]);

  return (
    <div className="relative size-full min-h-full overflow-hidden bg-[#05070d]">
      <div ref={containerRef} className="absolute inset-0" />
      {/* Cinematic vignette to focus the eye on the globe. */}
      <div className="pointer-events-none absolute inset-0 [background:radial-gradient(circle_at_50%_45%,transparent_42%,rgba(5,7,13,0.55)_100%)]" />
      <GlobeStatusOverlay
        events={events}
        globeTotal={globeTotal}
        globeLoading={globeLoading}
        globeLoadingMore={globeLoadingMore}
      />
    </div>
  );
}
