import { useEffect, useMemo, useRef } from "react";
import {
  ArcType,
  Cartesian3,
  Color,
  ColorMaterialProperty,
  ConstantProperty,
  GeoJsonDataSource,
  Ion,
  JulianDate,
  Math as CesiumMath,
  PointPrimitive,
  PointPrimitiveCollection,
  PolylineGraphics,
  Rectangle,
  ScreenSpaceEventHandler,
  ScreenSpaceEventType,
  SingleTileImageryProvider,
  UrlTemplateImageryProvider,
  Viewer,
  type ImageryLayer,
} from "cesium";
import "cesium/Build/Cesium/Widgets/widgets.css";
import type { Event } from "@/types/event";
import type { GlobeBBox } from "@/lib/events-api";
import { bboxChanged, viewBoundsToBBox } from "@/components/globe/cesium/viewport";
import { useAuth } from "@/hooks/useAuth";
import { type GlobeLayers, isQuake } from "@/components/globe/layers";
import {
  type GlobeCluster,
  type ScreenClusters,
  SEVERITY_ORDER,
  SEVERITY_RANK,
} from "@/components/globe/cesium/clusters";
import type {
  ClusterDataMessage,
  ClusterQueryMessage,
  ClusterResultMessage,
} from "@/components/globe/cesium/cluster-grid";
import {
  desiredCellDeg,
  LEVEL_CELL_DEG,
  pickLevelIndexWithHysteresis,
  UNCLUSTER_CELL_DEG,
  UNCLUSTER_LEVEL,
} from "@/components/globe/cesium/lod";
import {
  clusterDotStyle,
  dotPixelScaleForHeight,
  QUAKE_DOT_PIXEL_SIZE,
  quakePointStyle,
  selectionRingStyle,
} from "@/components/globe/cesium/quake-dots";
import { severityToCesiumColor } from "@/components/globe/cesium/severity-colors";
import { buildHeatCanvas } from "@/components/globe/cesium/heat";
import { createPoleUnderlayCanvas, DAYMAP_URL } from "@/components/globe/cesium/pole-underlay";
import { getTilesSession, sentinel2TemplateUrl } from "@/lib/tiles-api";
import { GlobeStatusOverlay } from "@/components/globe/cesium/GlobeStatusOverlay";
import {
  rebuildWeatherLayer,
  refreshWeatherSelection,
  weatherEventIdFromPick,
} from "@/components/globe/cesium/weather-areas";

/** EOX licensing credit shown in the Cesium credit container. */
const EOX_CREDIT = "Sentinel-2 cloudless by EOX IT Services GmbH (CC-BY 4.0)";

/** Local offline contour basemap (generated by scripts/gen-contour-tiles). */
const CONTOUR_TILES_URL =
  (import.meta.env.VITE_CONTOUR_TILES_URL as string | undefined) ?? "/contours/{z}/{x}/{y}.jpg";

/**
 * Web Mercator tiles only cover this latitude band; pole caps use a generated
 * underlay that samples Sentinel colors at the Mercator edge.
 */
const WEB_MERCATOR_RECTANGLE = Rectangle.fromDegrees(-180, -85.05112878, 180, 85.05112878);

/**
 * Fallback imagery zoom ceiling used only if the tiles session omits a usable
 * `max_zoom`. The authoritative value comes from the API (`tiles_max_zoom`) via
 * `/tiles/session`, so a storage-constrained deployment can lower it in config
 * and the globe stops requesting (and the proxy stops caching) deeper tiles.
 */
const DEFAULT_MAX_IMAGERY_LEVEL = 12;

/** Deep-zoom camera limits (meters from the surface). */
const MIN_ZOOM_METERS = 80;
const MAX_ZOOM_METERS = 4.5e7;

/** Country-border GeoJSON LOD: coarse always, finer once zoomed in. */
const BORDER_LODS = [
  { url: "/geo/ne_110m_admin_0_countries.geojson", maxHeightMeters: Infinity },
  { url: "/geo/ne_50m_admin_0_countries.geojson", maxHeightMeters: 4.0e6 },
  { url: "/geo/ne_10m_admin_0_countries.geojson", maxHeightMeters: 9.0e5 },
];
/** Coastline GeoJSON, loaded once zoomed in (raster carries the wide view). */
const COASTLINE_LOD = { url: "/geo/ne_50m_land.geojson", maxHeightMeters: 4.0e6 };

/** Upper bound on cached dot positions before the cache is reset (memory guard). */
const POSITION_CACHE_MAX = 250_000;

/** Picked-primitive identity stored on each Cesium point/label. */
type PickId = { kind: "single"; event: Event } | { kind: "cluster"; cluster: GlobeCluster };

interface CesiumGlobeViewportProps {
  events: Event[];
  /** Active weather/alert overlays (polygons or fallback markers). */
  weatherEvents?: Event[];
  selectedId: string | null;
  onSelect: (id: string) => void;
  onSelectCluster?: (cluster: GlobeCluster) => void;
  onClearSelection?: () => void;
  layers: GlobeLayers;
  globeTotal?: number;
  globeWeatherTotal?: number;
  globeLoading?: boolean;
  globeWeatherLoading?: boolean;
  globeLoadingMore?: boolean;
  globeEpoch?: number;
  /**
   * Called on camera settle with the current view bounds (margin-expanded), or
   * `null` for whole-globe/antimeridian views. Drives viewport-scoped loading.
   */
  onViewportChange?: (bbox: GlobeBBox | null) => void;
}

/**
 * CesiumJS globe implementing the same prop contract as the r3f `GlobeViewport`.
 * Imagery is a local Sentinel-2 tile pyramid served by the caching tile proxy;
 * Cesium's native quadtree LOD gives sharp, smooth zoom. Event dots, clustering,
 * selection + cluster-to-sidebar, heat overlay, vector borders, layer toggles,
 * status overlay, and live updates preserve the previous globe's behavior.
 */
export function CesiumGlobeViewport({
  events,
  weatherEvents = [],
  selectedId,
  onSelect,
  onSelectCluster,
  onClearSelection,
  layers,
  globeTotal,
  globeWeatherTotal,
  globeLoading,
  globeWeatherLoading,
  globeLoadingMore,
  globeEpoch = 0,
  onViewportChange,
}: CesiumGlobeViewportProps) {
  const { getAccessToken } = useAuth();
  const containerRef = useRef<HTMLDivElement | null>(null);
  const viewerRef = useRef<Viewer | null>(null);

  // Mutable handles for imperative Cesium objects rebuilt as props change.
  const singlesRef = useRef<PointPrimitiveCollection | null>(null);
  const clustersRef = useRef<PointPrimitiveCollection | null>(null);
  const selectionRef = useRef<PointPrimitiveCollection | null>(null);
  const heatLayerRef = useRef<ImageryLayer | null>(null);
  const weatherDataSourceRef = useRef<GeoJsonDataSource | null>(null);
  // Clustering runs in a Web Worker over typed arrays; the main thread keeps the
  // matching `Event[]` to map worker-returned indices back for rendering/picking.
  const workerRef = useRef<Worker | null>(null);
  const dataVersionRef = useRef(0);
  const datasetEventsRef = useRef<Event[]>([]);
  const requestIdRef = useRef(0);
  const latestRequestIdRef = useRef(0);
  const lastAppliedVersionRef = useRef(-1);
  const currentLevelRef = useRef<number | null>(null);
  // Keyed primitive maps enable incremental diffing (add/remove/restyle only the
  // dots that changed) instead of a full removeAll + re-add on every pan.
  const singleByKeyRef = useRef<Map<string, PointPrimitive>>(new Map());
  const clusterByKeyRef = useRef<Map<string, PointPrimitive>>(new Map());
  // Cache event id → Cartesian3 so repeated rebuilds (every zoom/LOD step) reuse
  // positions instead of recomputing `fromDegrees` (trig + allocation) per dot.
  const positionCacheRef = useRef<Map<string, Cartesian3>>(new Map());
  const lastLevelKeyRef = useRef<number>(-1);
  const lastDotScaleKeyRef = useRef<number>(-1);
  const lastRenderViewRef = useRef<GlobeBBox | null>(null);
  const loadedVectorUrls = useRef<Set<string>>(new Set());
  // Latest rendered singles/clusters so the selection ring can be placed on the
  // marker actually on screen (a cluster bubble or the event's own dot).
  const lastResultRef = useRef<ScreenClusters | null>(null);
  const selectedIdRef = useRef<string | null>(selectedId);
  // Throttle the expensive index + primitive rebuild while map batches stream in
  // so accumulating ~100k points stays responsive instead of rebuilding on every
  // batch. `quakeEventsRef` lets the trailing rebuild read the latest set.
  const rebuildTimerRef = useRef<number | undefined>(undefined);
  const prevQuakeCountRef = useRef(0);
  const lastApplyAtRef = useRef(0);
  const quakeEventsRef = useRef<Event[]>([]);
  const weatherEventsRef = useRef<Event[]>([]);
  // Viewport-scoped loading: report the camera bounds on settle so the page can
  // fetch only the visible quakes. `lastReportedBboxRef` suppresses tiny pans.
  const onViewportChangeRef = useRef(onViewportChange);
  onViewportChangeRef.current = onViewportChange;
  const lastReportedBboxRef = useRef<GlobeBBox | null>(null);

  // Latest props captured in refs so the imperative Cesium callbacks (created
  // once on mount) always read current values without re-binding listeners.
  const eventsRef = useRef(events);
  const layersRef = useRef(layers);
  const onSelectRef = useRef(onSelect);
  const onSelectClusterRef = useRef(onSelectCluster);
  const onClearSelectionRef = useRef(onClearSelection);
  eventsRef.current = events;
  layersRef.current = layers;
  onSelectRef.current = onSelect;
  onSelectClusterRef.current = onSelectCluster;
  onClearSelectionRef.current = onClearSelection;
  selectedIdRef.current = selectedId;

  const quakeEvents = useMemo(() => events.filter(isQuake), [events]);
  quakeEventsRef.current = quakeEvents;
  weatherEventsRef.current = weatherEvents;

  // ── Mount: build the viewer, imagery, handlers (once) ───────────────────────
  useEffect(() => {
    if (!containerRef.current) {
      return;
    }
    // No Cesium Ion assets are used; clear the default token to avoid network.
    Ion.defaultAccessToken = "";

    const viewer = new Viewer(containerRef.current, {
      baseLayer: false,
      animation: false,
      timeline: false,
      baseLayerPicker: false,
      geocoder: false,
      homeButton: false,
      sceneModePicker: false,
      navigationHelpButton: false,
      fullscreenButton: false,
      infoBox: false,
      selectionIndicator: false,
      // Keep the credit container visible for the required EOX attribution.
    });
    viewerRef.current = viewer;

    const scene = viewer.scene;
    scene.backgroundColor = Color.fromCssColorString("#05070d");
    scene.globe.baseColor = Color.fromCssColorString("#0b1a2b");
    if (scene.skyAtmosphere) {
      scene.skyAtmosphere.show = true;
    }
    scene.globe.showGroundAtmosphere = true;
    scene.fog.enabled = true;

    const controller = scene.screenSpaceCameraController;
    controller.minimumZoomDistance = MIN_ZOOM_METERS;
    controller.maximumZoomDistance = MAX_ZOOM_METERS;
    controller.enableCollisionDetection = true;

    // Imperative primitive collections for quake dots and selection ring.
    const singles = scene.primitives.add(new PointPrimitiveCollection());
    const clusters = scene.primitives.add(new PointPrimitiveCollection());
    const selection = scene.primitives.add(new PointPrimitiveCollection());
    singlesRef.current = singles;
    clustersRef.current = clusters;
    selectionRef.current = selection;

    // Clustering worker: bins ~100k points off the main thread and returns the
    // view-culled singles/clusters; results applied via incremental diff.
    const clusterWorker = new Worker(new URL("./clusters.worker.ts", import.meta.url), {
      type: "module",
    });
    clusterWorker.onmessage = handleWorkerMessage;
    workerRef.current = clusterWorker;

    // Pick handling: single dot → select; cluster → fly + open sidebar; miss → clear.
    const handler = new ScreenSpaceEventHandler(scene.canvas);
    handler.setInputAction((movement: ScreenSpaceEventHandler.PositionedEvent) => {
      const picked = scene.pick(movement.position);
      const weatherId = weatherEventIdFromPick(picked, weatherEventsRef.current);
      if (weatherId) {
        onSelectRef.current(weatherId);
        return;
      }
      const id = picked?.id as PickId | undefined;
      if (id && typeof id === "object" && "kind" in id) {
        if (id.kind === "single") {
          onSelectRef.current(id.event.id);
        } else {
          const { cluster } = id;
          viewer.camera.flyTo({
            destination: Cartesian3.fromDegrees(
              cluster.lon,
              cluster.lat,
              Math.max(viewer.camera.positionCartographic.height * 0.45, 4.0e5),
            ),
            duration: 0.8,
          });
          onSelectClusterRef.current?.(cluster);
        }
        return;
      }
      onClearSelectionRef.current?.();
    }, ScreenSpaceEventType.LEFT_CLICK);

    // Rebuild clusters while zooming (debounced) and once the camera settles.
    let clusterRebuildTimer: number | undefined;
    const scheduleClusterRebuild = () => {
      if (clusterRebuildTimer) {
        window.clearTimeout(clusterRebuildTimer);
      }
      clusterRebuildTimer = window.setTimeout(() => {
        clusterRebuildTimer = undefined;
        requestClusters();
      }, 120);
    };
    const onCameraSettle = () => {
      if (clusterRebuildTimer) {
        window.clearTimeout(clusterRebuildTimer);
        clusterRebuildTimer = undefined;
      }
      requestClusters();
      // Refine border/coastline LOD for the new zoom; idempotent (skips already
      // loaded levels). Camera-driven so it no longer runs per streamed batch.
      void loadVectorOverlays();
      maybeReportViewport();
    };
    viewer.camera.changed.addEventListener(scheduleClusterRebuild);
    viewer.camera.moveEnd.addEventListener(onCameraSettle);

    // Imagery stack (bottom → top): equirectangular pole underlay, optional
    // contour Mercator tiles, Sentinel Mercator tiles. Mercator layers declare
    // WEB_MERCATOR_RECTANGLE so Cesium composites the underlay at the poles.
    let cancelled = false;
    let sentinelLayer: ImageryLayer | null = null;

    const installPoleUnderlay = async (tilesToken?: string) => {
      const addProvider = async (url: string) => {
        const provider = await SingleTileImageryProvider.fromUrl(url, {
          rectangle: Rectangle.fromDegrees(-180, -90, 180, 90),
        });
        if (!cancelled && !viewer.isDestroyed()) {
          viewer.imageryLayers.addImageryProvider(provider, 0);
        }
      };

      try {
        const canvas = await createPoleUnderlayCanvas(tilesToken);
        // JPEG keeps the underlay fully opaque — Cesium can leave holes with PNG alpha.
        await addProvider(canvas.toDataURL("image/jpeg", 0.92));
      } catch {
        try {
          await addProvider(DAYMAP_URL);
        } catch {
          // Polar caps fall back to globe.baseColor.
        }
      }
    };

    const installContourFallback = async () => {
      const probeUrl = CONTOUR_TILES_URL.replace("{z}", "0")
        .replace("{x}", "0")
        .replace("{y}", "0");
      // No contour tiles served (404 / network error): skip the fallback layer.
      const available = await fetch(probeUrl, { method: "GET" })
        .then((res) => res.ok)
        .catch(() => false);
      if (!available || cancelled || viewer.isDestroyed()) {
        return;
      }
      const contourLayer = viewer.imageryLayers.addImageryProvider(
        new UrlTemplateImageryProvider({
          url: CONTOUR_TILES_URL,
          maximumLevel: 8,
          rectangle: WEB_MERCATOR_RECTANGLE,
          credit: "Elevation contours (ETOPO 2022, public domain)",
        }),
        1,
      );
      contourLayer.show = true;
    };

    // Fetch a tiles token, then add the Sentinel imagery layer above contours.
    let refreshTimer: number | undefined;
    const installSentinel = async (existingToken?: string) => {
      const token = existingToken ?? (await getAccessToken());
      if (!token || cancelled) {
        return;
      }
      let session;
      try {
        session = await getTilesSession(token);
      } catch {
        return; // Offline / unauthorized: contour fallback remains visible.
      }
      if (cancelled || viewer.isDestroyed()) {
        return;
      }
      const maximumLevel =
        Number.isFinite(session.max_zoom) && session.max_zoom > 0
          ? session.max_zoom
          : DEFAULT_MAX_IMAGERY_LEVEL;
      const provider = new UrlTemplateImageryProvider({
        url: sentinel2TemplateUrl(session.token),
        maximumLevel,
        rectangle: WEB_MERCATOR_RECTANGLE,
        credit: EOX_CREDIT,
      });
      if (sentinelLayer) {
        viewer.imageryLayers.remove(sentinelLayer, true);
        sentinelLayer = null;
      }
      sentinelLayer = viewer.imageryLayers.addImageryProvider(provider);
      // Refresh the token shortly before expiry so the imagery URL stays valid.
      const refreshMs = Math.max((session.expires_in - 300) * 1000, 60_000);
      refreshTimer = window.setTimeout(() => void installSentinel(), refreshMs);
    };

    void (async () => {
      const accessToken = await getAccessToken();
      let tilesToken: string | undefined;
      if (accessToken) {
        try {
          const session = await getTilesSession(accessToken);
          tilesToken = session.token;
        } catch {
          // Pole fill uses daymap + fallback colors when the session is unavailable.
        }
      }
      await installPoleUnderlay(tilesToken);
      await installContourFallback();
      await installSentinel(accessToken ?? undefined);
    })();

    void loadVectorOverlays();
    requestClusters();

    return () => {
      cancelled = true;
      if (clusterRebuildTimer) {
        window.clearTimeout(clusterRebuildTimer);
      }
      if (rebuildTimerRef.current !== undefined) {
        window.clearTimeout(rebuildTimerRef.current);
        rebuildTimerRef.current = undefined;
      }
      if (refreshTimer) {
        window.clearTimeout(refreshTimer);
      }
      clusterWorker.terminate();
      workerRef.current = null;
      viewer.camera.changed.removeEventListener(scheduleClusterRebuild);
      viewer.camera.moveEnd.removeEventListener(onCameraSettle);
      handler.destroy();
      if (!viewer.isDestroyed()) {
        viewer.destroy();
      }
      viewerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount-once viewer; props read via refs
  }, []);

  // ── Clustering pipeline (worker + culling + incremental diff) ───────────────

  /** Cartesian3 for an event, cached by id (positions are stable per id). */
  function positionForEvent(event: Event): Cartesian3 {
    const cache = positionCacheRef.current;
    let position = cache.get(event.id);
    if (!position) {
      position = Cartesian3.fromDegrees(event.location.lon, event.location.lat);
      if (cache.size < POSITION_CACHE_MAX) {
        cache.set(event.id, position);
      }
    }
    return position;
  }

  /** Drop all rendered dots and reset render bookkeeping. */
  function clearDots() {
    singlesRef.current?.removeAll();
    clustersRef.current?.removeAll();
    singleByKeyRef.current.clear();
    clusterByKeyRef.current.clear();
    lastLevelKeyRef.current = -1;
    lastDotScaleKeyRef.current = -1;
    lastRenderViewRef.current = null;
    lastResultRef.current = null;
  }

  /** Cheap path for intra-level zoom: only the dot pixel size changed. */
  function restyleDotsInPlace(pixelSize: number) {
    const singles = singlesRef.current;
    const clusters = clustersRef.current;
    if (singles) {
      for (let i = 0; i < singles.length; i += 1) {
        singles.get(i).pixelSize = pixelSize;
      }
    }
    if (clusters) {
      for (let i = 0; i < clusters.length; i += 1) {
        clusters.get(i).pixelSize = pixelSize;
      }
    }
  }

  /** Extract typed arrays from events and hand the dataset to the worker. */
  function sendDataToWorker(quakes: Event[]) {
    const worker = workerRef.current;
    if (!worker) {
      return;
    }
    const n = quakes.length;
    const lon = new Float64Array(n);
    const lat = new Float64Array(n);
    const severityRank = new Uint8Array(n);
    const impact = new Float32Array(n);
    for (let i = 0; i < n; i += 1) {
      const event = quakes[i];
      lon[i] = event.location.lon;
      lat[i] = event.location.lat;
      severityRank[i] = SEVERITY_RANK[event.severity] ?? 0;
      impact[i] = event.impact_score;
    }
    dataVersionRef.current += 1;
    datasetEventsRef.current = quakes;
    positionCacheRef.current.clear();
    const message: ClusterDataMessage = {
      type: "data",
      version: dataVersionRef.current,
      lon: lon.buffer,
      lat: lat.buffer,
      severityRank: severityRank.buffer,
      impact: impact.buffer,
      count: n,
    };
    worker.postMessage(message, [lon.buffer, lat.buffer, severityRank.buffer, impact.buffer]);
  }

  /**
   * Pick the LOD level + cull rectangle for the current camera and ask the
   * worker for the visible singles/clusters. Short-circuits to an in-place
   * restyle when only the dot pixel size changed (no LOD/view change).
   */
  function requestClusters(force = false) {
    const viewer = viewerRef.current;
    const worker = workerRef.current;
    if (!viewer || !worker || viewer.isDestroyed()) {
      return;
    }
    if (!layersRef.current.quakeDots || datasetEventsRef.current.length === 0) {
      clearDots();
      applySelectionHighlight();
      return;
    }

    const camera = viewer.camera;
    const height = camera.positionCartographic?.height ?? MAX_ZOOM_METERS;
    const fovy = (viewer.scene.camera.frustum as { fovy?: number }).fovy ?? CesiumMath.toRadians(60);
    const canvasHeight = viewer.scene.canvas.clientHeight || 1;
    const deg = desiredCellDeg(height, fovy, canvasHeight);

    let levelKey: number;
    let cellDeg: number;
    let uncluster: boolean;
    if (deg <= UNCLUSTER_CELL_DEG) {
      levelKey = UNCLUSTER_LEVEL;
      cellDeg = UNCLUSTER_CELL_DEG;
      uncluster = true;
      currentLevelRef.current = UNCLUSTER_LEVEL;
    } else {
      const level = pickLevelIndexWithHysteresis(deg, currentLevelRef.current);
      currentLevelRef.current = level;
      levelKey = level;
      cellDeg = LEVEL_CELL_DEG[level];
      uncluster = false;
    }

    const dotScale = dotPixelScaleForHeight(height, MAX_ZOOM_METERS);
    const dotScaleKey = Math.round(dotScale * 20);

    const rect = camera.computeViewRectangle();
    const renderView = rect
      ? viewBoundsToBBox(
          CesiumMath.toDegrees(rect.west),
          CesiumMath.toDegrees(rect.south),
          CesiumMath.toDegrees(rect.east),
          CesiumMath.toDegrees(rect.north),
        )
      : null;

    // Nothing structural changed: at most restyle dots for the new zoom.
    if (
      !force &&
      levelKey === lastLevelKeyRef.current &&
      !bboxChanged(lastRenderViewRef.current, renderView)
    ) {
      if (dotScaleKey !== lastDotScaleKeyRef.current) {
        restyleDotsInPlace(QUAKE_DOT_PIXEL_SIZE * dotScale);
        lastDotScaleKeyRef.current = dotScaleKey;
      }
      applySelectionHighlight();
      return;
    }

    lastRenderViewRef.current = renderView;
    const requestId = (requestIdRef.current += 1);
    latestRequestIdRef.current = requestId;
    const query: ClusterQueryMessage = {
      type: "query",
      version: dataVersionRef.current,
      requestId,
      levelKey,
      cellDeg,
      uncluster,
      view: renderView
        ? {
            west: renderView.minLon,
            south: renderView.minLat,
            east: renderView.maxLon,
            north: renderView.maxLat,
          }
        : null,
    };
    worker.postMessage(query);
  }

  /** Apply the latest worker result to Cesium (full rebuild or incremental diff). */
  function applyClusterResult(message: ClusterResultMessage) {
    const singles = singlesRef.current;
    const clusters = clustersRef.current;
    const viewer = viewerRef.current;
    if (!singles || !clusters || !viewer || viewer.isDestroyed()) {
      return;
    }

    const events = datasetEventsRef.current;
    const height = viewer.camera.positionCartographic?.height ?? MAX_ZOOM_METERS;
    const dotScale = dotPixelScaleForHeight(height, MAX_ZOOM_METERS);
    const pixelSize = QUAKE_DOT_PIXEL_SIZE * dotScale;

    // Map worker indices/ranks back to Event objects for rendering + picking.
    const singleEvents: Event[] = [];
    for (let i = 0; i < message.singleIndices.length; i += 1) {
      const event = events[message.singleIndices[i]];
      if (event) {
        singleEvents.push(event);
      }
    }
    const clusterList: GlobeCluster[] = message.clusters.map((cluster) => {
      const members: Event[] = [];
      for (const index of cluster.memberIndices) {
        const event = events[index];
        if (event) {
          members.push(event);
        }
      }
      const severity = SEVERITY_ORDER[cluster.severityRank] ?? "info";
      const anchorId = members[0]?.id ?? cluster.cellKey;
      return {
        id: `cl_${anchorId}_${cluster.count}`,
        lon: cluster.lon,
        lat: cluster.lat,
        count: cluster.count,
        members,
        color: severityToCesiumColor(severity),
        severity,
      };
    });

    const singleByKey = singleByKeyRef.current;
    const clusterByKey = clusterByKeyRef.current;
    const fullRebuild =
      message.version !== lastAppliedVersionRef.current || message.levelKey !== lastLevelKeyRef.current;

    if (fullRebuild) {
      singles.removeAll();
      clusters.removeAll();
      singleByKey.clear();
      clusterByKey.clear();
      for (const event of singleEvents) {
        singleByKey.set(
          event.id,
          singles.add({
            position: positionForEvent(event),
            color: severityToCesiumColor(event.severity),
            pixelSize,
            outlineWidth: 0,
            id: { kind: "single", event } satisfies PickId,
          }),
        );
      }
      for (const cluster of clusterList) {
        clusterByKey.set(
          cluster.id,
          clusters.add({
            position: Cartesian3.fromDegrees(cluster.lon, cluster.lat),
            ...clusterDotStyle(cluster.severity, dotScale),
            id: { kind: "cluster", cluster } satisfies PickId,
          }),
        );
      }
    } else {
      // Incremental diff: add entering dots, remove leaving, restyle the rest.
      const nextSingleKeys = new Set<string>();
      for (const event of singleEvents) {
        nextSingleKeys.add(event.id);
      }
      for (const [key, primitive] of singleByKey) {
        if (!nextSingleKeys.has(key)) {
          singles.remove(primitive);
          singleByKey.delete(key);
        }
      }
      for (const event of singleEvents) {
        const existing = singleByKey.get(event.id);
        if (existing) {
          existing.pixelSize = pixelSize;
        } else {
          singleByKey.set(
            event.id,
            singles.add({
              position: positionForEvent(event),
              color: severityToCesiumColor(event.severity),
              pixelSize,
              outlineWidth: 0,
              id: { kind: "single", event } satisfies PickId,
            }),
          );
        }
      }

      const nextClusterKeys = new Set<string>();
      for (const cluster of clusterList) {
        nextClusterKeys.add(cluster.id);
      }
      for (const [key, primitive] of clusterByKey) {
        if (!nextClusterKeys.has(key)) {
          clusters.remove(primitive);
          clusterByKey.delete(key);
        }
      }
      for (const cluster of clusterList) {
        const existing = clusterByKey.get(cluster.id);
        if (existing) {
          existing.pixelSize = pixelSize;
          existing.id = { kind: "cluster", cluster } satisfies PickId;
        } else {
          clusterByKey.set(
            cluster.id,
            clusters.add({
              position: Cartesian3.fromDegrees(cluster.lon, cluster.lat),
              ...clusterDotStyle(cluster.severity, dotScale),
              id: { kind: "cluster", cluster } satisfies PickId,
            }),
          );
        }
      }
    }

    lastAppliedVersionRef.current = message.version;
    lastLevelKeyRef.current = message.levelKey;
    lastDotScaleKeyRef.current = Math.round(dotScale * 20);
    lastResultRef.current = { singles: singleEvents, clusters: clusterList };
    applySelectionHighlight();
  }

  /** Apply worker results, dropping stale data versions and superseded queries. */
  function handleWorkerMessage(event: MessageEvent<ClusterResultMessage>) {
    const message = event.data;
    if (
      message.type !== "result" ||
      message.version !== dataVersionRef.current ||
      message.requestId !== latestRequestIdRef.current
    ) {
      return;
    }
    applyClusterResult(message);
  }

  // ── Selection highlight, aligned to the visible marker ──────────────────────
  // Places the ring on the marker the user actually sees: the cluster bubble
  // when the selected event is aggregated into one (anchored on the top-impact
  // member, which may differ from other members), otherwise the event's own dot. Reads refs so
  // it can be called from both `applyClusterResult` and the selection effect.
  function applySelectionHighlight() {
    const selection = selectionRef.current;
    if (!selection) {
      return;
    }
    selection.removeAll();
    const selectedId = selectedIdRef.current;
    if (!selectedId) {
      return;
    }

    const viewer = viewerRef.current;
    const height = viewer?.camera.positionCartographic?.height ?? MAX_ZOOM_METERS;
    const dotScale = dotPixelScaleForHeight(height, MAX_ZOOM_METERS);

    const cluster = lastResultRef.current?.clusters.find((item) =>
      item.members.some((member) => member.id === selectedId),
    );
    if (cluster) {
      const position = Cartesian3.fromDegrees(cluster.lon, cluster.lat);
      selection.add({ position, ...clusterDotStyle(cluster.severity, dotScale) });
      selection.add({
        position,
        ...selectionRingStyle(QUAKE_DOT_PIXEL_SIZE * dotScale + 10),
      });
      return;
    }

    const event =
      lastResultRef.current?.singles.find((item) => item.id === selectedId) ??
      eventsRef.current.find((item) => item.id === selectedId);
    if (!event) {
      return;
    }
    const position = Cartesian3.fromDegrees(event.location.lon, event.location.lat);
    // Draw the dot too so a selection that is not part of the current LOD (e.g.
    // hydrated from detail) is still visible inside the ring.
    selection.add({
      position,
      ...quakePointStyle(event.severity, dotScale, QUAKE_DOT_PIXEL_SIZE + 2),
    });
    selection.add({
      position,
      ...selectionRingStyle((QUAKE_DOT_PIXEL_SIZE + 2) * dotScale + 8),
    });
  }

  // ── Viewport reporting: drive page-side viewport-scoped loading ─────────────
  function maybeReportViewport() {
    const cb = onViewportChangeRef.current;
    const viewer = viewerRef.current;
    if (!cb || !viewer || viewer.isDestroyed()) {
      return;
    }
    const rect = viewer.camera.computeViewRectangle();
    const bbox = rect
      ? viewBoundsToBBox(
          CesiumMath.toDegrees(rect.west),
          CesiumMath.toDegrees(rect.south),
          CesiumMath.toDegrees(rect.east),
          CesiumMath.toDegrees(rect.north),
        )
      : null;
    if (!bboxChanged(lastReportedBboxRef.current, bbox)) {
      return;
    }
    lastReportedBboxRef.current = bbox;
    cb(bbox);
  }

  // ── Vector overlays (borders + coastline), camera-height LOD ────────────────
  async function loadVectorOverlays() {
    const viewer = viewerRef.current;
    if (!viewer || viewer.isDestroyed()) {
      return;
    }
    const height = viewer.camera.positionCartographic?.height ?? MAX_ZOOM_METERS;

    const wanted: { url: string; color: string; width: number }[] = [];
    // Finest qualifying border level only (last wins) + coastline when zoomed.
    let border = BORDER_LODS[0];
    for (const lod of BORDER_LODS) {
      if (height <= lod.maxHeightMeters) {
        border = lod;
      }
    }
    wanted.push({ url: border.url, color: "#cdf3ea", width: 1 });
    if (height <= COASTLINE_LOD.maxHeightMeters) {
      wanted.push({ url: COASTLINE_LOD.url, color: "#bfe9ff", width: 1 });
    }

    for (const item of wanted) {
      if (loadedVectorUrls.current.has(item.url)) {
        continue;
      }
      loadedVectorUrls.current.add(item.url);
      try {
        const ds = await GeoJsonDataSource.load(item.url, {
          stroke: Color.fromCssColorString(item.color).withAlpha(0.5),
          fill: Color.TRANSPARENT,
          strokeWidth: item.width,
        });
        // Replace every loaded polygon with a plain outline polyline drawn with
        // straight (ArcType.NONE), non-ground-clamped segments. Cesium's default
        // ground-clamped rhumb subdivision over the dense Natural Earth polygons
        // explodes the vertex count and crashes the renderer ("Too many
        // properties to enumerate"); filled polygon geometry with a forced
        // arcType/height fails differently. Since the fill is transparent and v1
        // uses a flat ellipsoid (no 3D terrain), straight chords between the
        // already-dense vertices look identical and never subdivide.
        const material = new ColorMaterialProperty(
          Color.fromCssColorString(item.color).withAlpha(0.5),
        );
        const now = JulianDate.now();
        for (const entity of ds.entities.values) {
          if (entity.polygon) {
            const hierarchy = entity.polygon.hierarchy?.getValue(now);
            const positions = hierarchy?.positions;
            entity.polygon = undefined;
            if (positions && positions.length > 1) {
              entity.polyline = new PolylineGraphics({
                positions,
                width: item.width,
                material,
                arcType: ArcType.NONE,
                clampToGround: false,
              });
            }
          } else if (entity.polyline) {
            entity.polyline.material = material;
            entity.polyline.width = new ConstantProperty(item.width);
            entity.polyline.arcType = new ConstantProperty(ArcType.NONE);
            entity.polyline.clampToGround = new ConstantProperty(false);
          }
        }
        if (viewer.isDestroyed()) {
          return;
        }
        await viewer.dataSources.add(ds);
      } catch {
        loadedVectorUrls.current.delete(item.url);
      }
    }
  }

  // ── React to event-set changes: rebuild the cluster index (throttled) ───────
  // While batches stream in (the set only grows), a full `O(n)` index + Cesium
  // primitive rebuild on every batch makes a large load `O(n²)` and janky. So we
  // render the first batch immediately, coalesce intermediate batches to at most
  // one rebuild per window, and always render the final batch via a trailing
  // timer that reads the latest set from `quakeEventsRef`.
  useEffect(() => {
    const REBUILD_THROTTLE_MS = 400;

    const applyEventSet = () => {
      const data = quakeEventsRef.current;
      lastApplyAtRef.current = performance.now();
      prevQuakeCountRef.current = data.length;
      // New dataset version → the next worker result triggers a full rebuild.
      sendDataToWorker(data);
      requestClusters(true);
    };

    const grewWhileStreaming =
      prevQuakeCountRef.current > 0 && quakeEvents.length > prevQuakeCountRef.current;
    const elapsed = performance.now() - lastApplyAtRef.current;

    if (!grewWhileStreaming || elapsed >= REBUILD_THROTTLE_MS) {
      // First load, filter reset/shrink, or throttle window elapsed: render now.
      if (rebuildTimerRef.current !== undefined) {
        window.clearTimeout(rebuildTimerRef.current);
        rebuildTimerRef.current = undefined;
      }
      applyEventSet();
    } else if (rebuildTimerRef.current === undefined) {
      // Trailing rebuild for the rest of the window; guarantees the last batch
      // renders even if it lands mid-window (timer reads the latest set).
      rebuildTimerRef.current = window.setTimeout(() => {
        rebuildTimerRef.current = undefined;
        applyEventSet();
      }, REBUILD_THROTTLE_MS - elapsed);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount-stable fns read via refs; key off the event set only
  }, [quakeEvents]);

  // ── React to layer toggles (dots) ───────────────────────────────────────────
  useEffect(() => {
    requestClusters(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount-stable fn read via refs; key off the toggle only
  }, [layers.quakeDots]);

  // ── Heat overlay: rebuild canvas layer on toggle / events / epoch ───────────
  useEffect(() => {
    const viewer = viewerRef.current;
    if (!viewer || viewer.isDestroyed()) {
      return;
    }
    const removeHeat = () => {
      if (heatLayerRef.current) {
        viewer.imageryLayers.remove(heatLayerRef.current, true);
        heatLayerRef.current = null;
      }
    };

    if (!layers.quakeHeat) {
      removeHeat();
      return;
    }

    // Debounce heavy repaints while batches stream in.
    const debounceMs = quakeEvents.length > 2_500 || globeLoadingMore ? 400 : 0;
    const timer = window.setTimeout(() => {
      if (viewer.isDestroyed()) {
        return;
      }
      const canvas = buildHeatCanvas(quakeEvents);
      removeHeat();
      if (!canvas) {
        return;
      }
      void SingleTileImageryProvider.fromUrl(canvas.toDataURL("image/png"), {
        rectangle: Rectangle.fromDegrees(-180, -90, 180, 90),
      }).then((provider) => {
        if (viewer.isDestroyed() || !layersRef.current.quakeHeat) {
          return;
        }
        heatLayerRef.current = viewer.imageryLayers.addImageryProvider(provider);
      });
    }, debounceMs);

    return () => window.clearTimeout(timer);
  }, [layers.quakeHeat, quakeEvents, globeEpoch, globeLoadingMore]);

  // ── Weather overlay: semi-transparent alert polygons / fallback markers ───
  useEffect(() => {
    const viewer = viewerRef.current;
    if (!viewer || viewer.isDestroyed()) {
      return;
    }
    let cancelled = false;
    void rebuildWeatherLayer(viewer, weatherDataSourceRef, weatherEvents, layers.weather).then(
      () => {
        if (cancelled) {
          return;
        }
        refreshWeatherSelection(
          weatherDataSourceRef.current,
          weatherEventsRef.current,
          selectedIdRef.current,
        );
      },
    );
    return () => {
      cancelled = true;
    };
  }, [weatherEvents, layers.weather]);

  // ── Selection highlight ─────────────────────────────────────────────────────
  useEffect(() => {
    applySelectionHighlight();
    refreshWeatherSelection(weatherDataSourceRef.current, weatherEvents, selectedId);
  }, [selectedId, events, weatherEvents]);

  return (
    <div className="relative size-full min-h-full overflow-hidden bg-[#05070d]">
      <div ref={containerRef} className="absolute inset-0" />
      {/* Cinematic vignette to focus the eye on the globe. */}
      <div className="pointer-events-none absolute inset-0 [background:radial-gradient(circle_at_50%_45%,transparent_42%,rgba(5,7,13,0.55)_100%)]" />
      <GlobeStatusOverlay
        events={events}
        weatherEvents={weatherEvents}
        globeTotal={globeTotal}
        globeWeatherTotal={globeWeatherTotal}
        globeLoading={globeLoading}
        globeWeatherLoading={globeWeatherLoading}
        globeLoadingMore={globeLoadingMore}
      />
    </div>
  );
}
